### ISSUE TITLE
encounter() support

### ISSUE THREAD

**Issue by NoonanM** [ctmm-initiative/ctmmweb#131] opened 2020-10-30 15:44 UTC
Integrate the encounter function from ctmm into ctmmweb.

https://www.biorxiv.org/content/biorxiv/early/2020/08/25/2020.08.24.261628.full.pdf

**Comment by xhdong-umd** [comment] 2020-11-01 14:36
duplicate of #132. I'm moving the comment there since that issue title have more details.

**Closed by xhdong-umd** 2020-11-01 14:36 UTC
