### ISSUE TITLE
Potential Feature: Movebank outlier identification

### ISSUE THREAD

**Issue by NoonanM** [ctmm-initiative/ctmmweb#72] opened 2018-09-14 08:32 UTC
On movebank, after uploading data, you can add an additional column at a later date with outlier information. More info here:
https://www.movebank.org/node/42

I wonder if it would be possible for users that are pulling in their data from Movebank to be able to either i) feed the outlier information from the app() back to movebank, or ii) if that's not possible at least generate a column that they could then add to Movebank manually.

**Comment by xhdong-umd** [comment] 2018-09-14 13:15
Do you have a sample data file that include the column `Manually marking outliers`? I have some data with this column but it's empty. I need to know the format and value for that column. It should be possible to add this column and export data, then we need to test if adding it back to movebank works.

**Comment by xhdong-umd** [comment] 2018-09-18 15:58
I wanted to try to upload some sample data and try the event editor by myself, but movebank said uploading any data must have the explicit permission from data owner. Is there any data can be used for testing movebank features? I'll make the data to be invisible to public to avoid confusions.

**Comment by NoonanM** [comment] 2018-09-25 19:18
Unfortunately, no I don't have any useful data for this. The idea came from a number of students at the Animove course. They thought it would be a nice way to keep their datasets up to date with the work they've done in ctmm.

Now that I think of it, it would probably be useful for us to have some generic testing data that we can play with in Movebank. I'll try and think about what we can use for that.

**Comment by xhdong-umd** [comment] 2018-10-15 18:33
Previously the removed outliers will be removed from data set in app. 

To add the outlier column, these outliers need to stay in the data set, just marked by the column. This also means the web app need to recognize it if the data set is imported again. Right now `as.telemetry` handled all data importing, but it probably will not recognize the outlier column and import them as regular points.

I can write code to process them first then feed to `as.telemetry`, but I'm not sure if @chfleming want to handle this column, or what's the best approach here.

@NoonanM 
I'm also not sure about how the web app should handle the data with this column. Should the outliers just be ignored in importing?

**Comment by xhdong-umd** [comment] 2018-10-24 18:12
@chfleming This is the documentation about the column in Movebank:

- [mark outliers in Movebank interface](https://www.movebank.org/node/42#mark_outliers)
- [attribute dictionary](https://www.movebank.org/node/2381)

> manually marked outlier: An event marked manually as an outlier, typically using the Event Editor in Movebank. Allowed values are TRUE or FALSE.

The column is named as `manually-marked-outlier` in downloaded Movebank file, but that is not a valid name in R, so I'm using `manually_marked_outlier` in my code. User need to map the column in uploading process anyway.

**Comment by chfleming** [comment] 2018-10-31 22:30
I added and documented a `mark.rm=FALSE` argument to `as.telemetry()` in the latest update.

**Comment by xhdong-umd** [comment] 2019-02-22 20:55
@chfleming I decided to still keep outliers out of main data structure, but write them back in export/save to csv. The csv can be recognized by movebank (you need to map columns no matter what).

However in testing `as.telemetry` with `mark.rm=FALSE`, I found [the code dropped the outliers here properly](https://github.com/ctmm-initiative/ctmm/blob/master/R/telemetry.R#L320), but the final result still have all the rows.

Here is some code and data to test:

[test data](https://drive.google.com/file/d/13SPmdCa1bHY_QVG7WZOd3Rsj9mvWLAoO/view?usp=sharing)

```r
library(ctmm)
# there should be 3 points removed from pepper so it will have 97 points.
tele_list <- as.telemetry("outlier_marked_2.csv", mark.rm = TRUE)
```

**Comment by chfleming** [comment] 2019-02-22 22:11
Thanks, just a silly bug on my part. Will be fixed in the next push.

`"manually_marked_outlier"` should be recognized. I convert all column names to lower case and treat `.`, `-`, `_`, `:`, ` `, `` as the same in `pull.column()`.

**Comment by xhdong-umd** [comment] 2019-02-25 15:32
I tested with latest ctmm and everything worked as expected. 

- Exported csv file will have outliers marked in column, import it back to app will have the outlier discarded.
- Restoring saved progress zip will have the outliers status restored because the zip have more complete information.

**Comment by xhdong-umd** [comment] 2019-03-05 19:33
@chfleming I found there is error when importing a movebank data set "FTZ_ Foraging in lesser black-backed gulls (data from Garthe et al. 2016)", [movebank id 183209639](https://www.movebank.org/movebank/#page=studies,path=study183209639). 

There is a "manually-marked-outlier" column but most values are empty. When importing with `mark.rm = TRUE` there is this error:

`<simpleError in as.POSIXct.default(x, tz = timezone): do not know how to convert 'x' to class “POSIXct”>
`

**Comment by chfleming** [comment] 2019-03-10 18:21
Looks like I didn't anticipate `NA` values in that column. Will be fixed in the next push.

**Comment by xhdong-umd** [comment] 2020-04-06 13:52
Reopen to discuss how ctmm and ctmmweb should handle `manually-marked-outlier` column.

**Comment by chfleming** [comment] 2020-04-06 19:41
`as.telemetry()` has a `mark.rm=FALSE` default argument for manually marked outliers. `ctmmweb` is effectively `mark.rm=TRUE` for default analysis. My preference is not to identify or toss out outliers until after users have dealt with error modeling. Sometimes there can be useful information in marked outliers. E.g., there can be an entire class of location fixes that needs to be removed, instead of just the few bad fixes you can easily see. Also, the quality of outlier classification coming in can be insufficient.

**Comment by xhdong-umd** [comment] 2020-04-08 21:21
@jmcalabrese  @chfleming If I'm understanding correctly, `mark.rm` will either remove manually marked outliers or treat them as normal data points. There is no option to accept them as outliers, right? That may surprise users when they move data processed in ctmmweb to ctmm. If you think they really should not just accept the outliers, maybe at least give a warning in `as.telemetry`?

**Comment by jmcalabrese** [comment] 2020-04-09 08:00
Saying what @xhdong-umd said another way: 

The fundamental difference here is that ctmm removes outliers from an analysis by completely removing them from the dataset, while ctmmweb leaves them in the dataset but marks them, and then uses the marks to exclude them from the analysis.

I think ctmm and ctmmweb need to use a common system for excluding outliers from an analysis. I am partial to the "mark and leave in the dataset" approach that ctmmweb uses.

**Comment by xhdong-umd** [comment] 2020-04-09 09:55
Agree. And the reason that these outliers need to exist in data came from the original request of uploading csv back to movebank and have them recognized by movebank.

**Comment by chfleming** [comment] 2020-04-09 20:00
I will add a warning when outliers are marked in the data and `rm.mark=FALSE`, though beyond that I'm not seeing a way to satisfy all criteria here.

By default I don't want to trust external outlier classification on import, which will often involve things like HDOP>10, which does not really denote an outlier. And I wouldn't want to import the outlier classifier column if its not going to be used as such.

Having an internal way to mark outliers on the command line without deleting them is possible but I don't see any purpose for that. What would the marked outliers ever get used for?

**Comment by xhdong-umd** [comment] 2020-04-09 21:31
The original design was for uploading data to movebank and make outliers be recognized by movebank. This means the rows in data can be valid or outliers, which make processing more difficult.
If this feature is not used frequently, we can put this as a special feature instead of default.

- There are several ways for user to export data in ctmmweb
  - export data as csv. I'll strip outliers in this case.
  - save progress as a zip. This has more complete data, restoring it doesn't use as.telemetry (I may need to confirm this). This can restore the outlier status by design, and user can continue work on it.
  - I'll add a button to export data with manually marked outlier column for movebank import purpose, explain this is different from regular csv.
- So user are expected to either use original data with ctmm, or use exported csv which have outliers stripped. They should not feed csv for movebank import to ctmm, and there should be a warning in ctmm when dealing with this kind of file. The warning should tell user the marked outliers can be removed or treat as normal data with parameter.
  I'll also add a warning in ctmmweb if user import such a file. This should ensure no surprise happen.

**Comment by jmcalabrese** [comment] 2020-04-10 16:34
@chfleming use cases for flagging (but not totally removing) outliers include:

- Checking if outliers substantially affect the results (i.e., doing an analysis with and without the outliers)
- Cases where a data point might be considered a "behavioral" outlier that might be excluded for some analyses but not others
- Future developments in movement and/or error models that might change a given point's status as an outlier

**Comment by chfleming** [comment] 2020-04-10 18:29
@xhdong-umd My thoughts are that `ctmmweb`  -> Movebank can be supported, but its probably not a good idea, in general, to go from analysis to archival (instead of reverse). On the other hand `ctmmweb` -> `ctmm` seems like a logical progression that we should support.

**Comment by chfleming** [comment] 2020-04-10 18:35
@jmcalabrese What would an outlier flagging function look like on the command line? On the back end it would have to pull the outliers out of the base data.frame and store them in a second data.frame in a special `@` slot. But on the front end, to the end user, what would this look like, functionally? I think it has to be at least as easy to use as basic subsetting to be worthwhile.

**Comment by NoonanM** [comment] 2020-04-10 19:06
@chfleming Could you not have an additional column in telemetry objects with an outlier dummy variable. Any of the machinery could then filter based on that column and everything would then run as normal. Functions could then have a drop.outliers argument that is set to TRUE by default, and you can set it to FALSE to test the sensitivity of an analysis to outliers.

**Comment by chfleming** [comment] 2020-04-10 19:37
@NoonanM That would work, but it would also involve modifying a ton of functions in the package. By moving the outliers out of the base object and into a separate slot (on the back end), everything works as is.

**Comment by xhdong-umd** [comment] 2020-05-06 19:25
I made these changes for marked outliers:
- There is a checkbox to keep outliers in exported csv. By default outliers are stripped. User can keep them as manually marked outliers, which is supposed to be used for movebank import. 
![image](https://user-images.githubusercontent.com/25039897/81219453-d098a400-8fad-11ea-954e-b9b0fe5a7927.png)

- Importing csv with manually marked outliers to ctmmweb will remove them, and there is warning in R console. I assume outliers are to be excluded once marked.
- If user removed some outliers and saved progress, restoring this progress zip will restore the outliers in outlier panel.

**Comment by xhdong-umd** [comment] 2020-05-06 19:32
I also added some help text for this in import page and export current page.

**Closed** 2020-05-10 18:19 UTC
