### ISSUE TITLE
Overlap

### ISSUE THREAD

**Issue by NoonanM** [ctmm-initiative/ctmmweb#36] opened 2017-10-19 16:41 UTC
Are there any plans to implement the overlap() function? My guess is a lot of users would want to use this function for subsequent analyses and it would be good to provide the option within the app.

**Comment by xhdong-umd** [comment] 2017-10-19 16:53
@chfleming @jmcalabrese What's the work flow you have in mind?

I saw `overlap` can be applied to `A list of ctmm fit, telemetry, or aligned UD objects`. So it can be 
- telemetry overlap for current selected individuals
- overlap for fitted models
- aligned home range
- aligned occurrence

There could be a button in each page, or one button to generate all available overlaps for current selected individuals/models/home ranges etc.

The result will be just some tables. How do you want to use the result for subsequent analyses?

**Comment by chfleming** [comment] 2017-10-19 18:25
You want the UD overlap only for now, after home range-analysis.

If you calculate all of the UDs on the same grid by feeding them all into `akde()` at once, then you can more quickly calculate UD overlap from the existing UD objects (+ fit object argument).

**Comment by NoonanM** [comment] 2017-10-19 18:44
Most appropriate would probably be an 'Overlap' tab since it's a tangential analysis that people don't have to do, but many will probably want to. But I leave that choice to @chfleming and @jmcalabrese.

My guess is users wanting to estimate overlap will generally use all individuals included in the Home Range tab.

Output is three matrices. I've found visualizing them via the attached ggplot script to be a useful way of quickly seeing what's happening. BC is an object output from overlap()

`dis <- as.matrix(BC[,,2]) #This one plots the point estimate [,,1] and [,,3] are the CIs
#dis[upper.tri(dis, diag = FALSE)] <- NA
dis <- data.table::melt(dis, na.rm = TRUE)
dis$value <- log(dis$value) #Usually have to log scale to make the colors stand out more



ggplot(dis, aes(Var1,Var2, fill=value)) +
  geom_tile(color = "black") + theme_bw()+
  theme(panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.text.y  =  element_text(size=6, hjust=1, vjust = 0, family = "serif"),
        axis.title.y  = element_blank(), axis.ticks.y = element_blank(),
        axis.title.x  = element_blank(),
        axis.text.x  = element_text(angle=90, size=6, hjust=1, vjust = 0, family = "serif"),
        legend.background = element_blank(),
        legend.text = element_text(size=4),
        legend.key.size = unit(0.4, "cm"),
        legend.title=element_blank()) +
  viridis::scale_fill_viridis(na.value = '#440154FF')`

[Distances.pdf](https://github.com/ctmm-initiative/ctmm-webapp/files/1399550/Distances.pdf)

If you could have a set up where the user can click on a tile that looks interesting, and they would see the two (or more?) UDs plotted together my guess is many users would find that useful.

**Comment by xhdong-umd** [comment] 2017-10-25 16:55
I'm working on maps now, probably will revisit this after maps are finished.

**Comment by NoonanM** [comment] 2017-10-25 19:06
@xhdong-umd That's fine. We are currently working on the paper that will accompany the overlap() function. Ideally we would have the two come out around the same time (app functionality and paper), but the paper is still a few months away from publication so there is plenty of time.

**Comment by xhdong-umd** [comment] 2018-01-11 20:21
I haven't read the full paper yet. Based on the help of `overlap` and discussions above

- we can have overlap for gaussian distribution of models, or home ranges.
- we can use the selected models in the model summary table, and the selected home ranges in home range table as the basis of overlap. By default it will select the best model for each animal. The home range table have no selection now but it can be added. 

  This way user also have the flexibility to select any combination.
- In the model selection page
  - If we add a tab in model summary table box, user will not be able to see selected models and overlap result at the same time.
  - If we add a tab in variogram box, I felt it's kind of weird as the overlap is only available after models are generated and selected, thus should not be in same "level" of variogram. Though this is still an option.
  - We can also add an individual box of `Overlap`(we can also use a pop up window, but again, an individual box can keep the result better). And I can make the content in the box respond to the selections in model summary table dynamically. The performance will not be a problem since the overlap calculation for gaussian distribution is very fast. The negative of this option is user need to scroll a long page.
- For the home range page, we can either add an overlap box or add a overlap tab to home range plots.
  The overlap of 3 home ranges of buffalo took 15 seconds in my machine, so it's better to make it an option only activated by user.
- Thus the better option seemed to be adding a tab in variogram box and home range plot box. Once user clicked that tab, overlap of current selected models/home ranges will be calculated.
- Because the overlap of home range take longer time to calculate, maybe we should not select all home ranges by default? User can select some home ranges and click tab to check overlap. There can be a button to select all, just we don't put it as default.

For the representation of overlap results
- I think a table of numerical values is always needed. I can add a table, also save it in the work report.
- We definitely need some plot to visualize the result. The color scale doesn't seem to be very intuitive as a guide of 0-1 values to me. Maybe a grayscale or alpha scale of same color is better. And we may also only draw the triangle half of the matrix to reduce duplications.

  Or something like this
![ggplot_masterlist_9](https://user-images.githubusercontent.com/25039897/34845274-567edb5a-f6e2-11e7-9a14-edb32b209469.png)

I'll also explore some variations and compare the results. 
  - one option is pie chart, we can put a pie chart in each grid cell. I'm not sure it's doable with ggplot though.
  - another option is a bar with two segments to show the overlap percentage.
  - we can also just draw a scatter plot of x: animal a, animal b, animal c, y: 0 ~ 1, color (shape) of point: animal a, animal b, animal c.

**Comment by NoonanM** [comment] 2018-01-17 21:44
When plotting the matrix, in addition to the concentric circle style that @chfleming suggested, we can also make use of the two halves of the matrix to include more information as in this example:

![corr_mixed](https://user-images.githubusercontent.com/26824892/35068553-64216a80-fba5-11e7-9929-fd782d1788c4.png)

(This uses the corrplot.mixed() function from the corrplot package)

**Comment by chfleming** [comment] 2018-01-17 22:06
![circle](https://user-images.githubusercontent.com/19801979/35069579-954fc2f2-fba8-11e7-8a5d-b20020d3d7b4.png)

Here's a mock-up of what I was thinking, where the inner most circle radius would be the lower confidence interval, the middle circle radius would be the point estimate, and the outer circle radius would be the upper confidence interval.

**Comment by xhdong-umd** [comment] 2018-01-24 16:01
I'm thinking to use color background in the numeric table, which can serve like the overview plot. And use 1 dimension plot instead of a 2-d grid, because the grid gives a pattern which does not exist.

I'll try a arranged bar chart and wrapped facet. 1-d plot is also easy to compare values.

**Comment by xhdong-umd** [comment] 2018-01-25 16:47
This is the overview table. I plan to remove the duplicate half, use color background scaled to the value in the app.

<img width="587" alt="screen shot 2018-01-25 at 11 45 25 am" src="https://user-images.githubusercontent.com/25039897/35400667-6b31e6d0-01c5-11e8-9e0f-195bc4f1e782.png">

And a plot with error bar for all unique combinations

<img width="1385" alt="screen shot 2018-01-25 at 11 44 53 am" src="https://user-images.githubusercontent.com/25039897/35400694-7b0ea8d6-01c5-11e8-8d36-1f40d8640249.png">

**Comment by xhdong-umd** [comment] 2018-01-26 21:28
I made these changes to the table, try to make it easier to read:
- the low/high rows can be hidden with a checkbox
- the duplicate half can be removed with a checkbox
- the low/high rows have a grayscale background, just like the model summary table
- the value color is grayscale by the value.

<img width="947" alt="screen shot 2018-01-26 at 4 27 25 pm" src="https://user-images.githubusercontent.com/25039897/35461408-def99400-02b5-11e8-8ace-5ac3f22a1638.png">

**Comment by xhdong-umd** [comment] 2018-01-29 19:14
@jmcalabrese @chfleming @NoonanM The basic parts of the overlap page are ready now.

The different views of the summary table

<img width="976" alt="screen shot 2018-01-29 at 2 04 08 pm" src="https://user-images.githubusercontent.com/25039897/35528956-7d8799f2-04fd-11e8-95d8-61f90fb5769e.png">
<img width="981" alt="screen shot 2018-01-29 at 2 04 23 pm" src="https://user-images.githubusercontent.com/25039897/35528958-80460f20-04fd-11e8-89e1-b3fc6edbf12e.png">

The plot of the value range for each combination

<img width="985" alt="screen shot 2018-01-29 at 2 04 30 pm" src="https://user-images.githubusercontent.com/25039897/35528973-8ca3fc46-04fd-11e8-933b-09f56f60152b.png">

- the value label can be removed if needed
- I rotated the plot so more combinations will increase plot height instead of width, which should be easier to handle
- Note the y axis start from bottom, so the first values of the table appeared in bottom of the plot.

The `location` tab will show the animal locations plot.

I'm trying to add interactivity among the table and plots for now:
- clicking cells in the table will highlight the corresponding part in the value range plot, and the animal locations (draw other animals in grey background)
- clicking the value range plot should highlight the cells in the table

**Comment by xhdong-umd** [comment] 2018-01-30 22:05
I found this version of summary table is better than the 2d matrix table above:

<img width="681" alt="screen shot 2018-01-30 at 5 01 37 pm" src="https://user-images.githubusercontent.com/25039897/35593911-684b8dfe-05df-11e8-9a72-8d875d5f1e8e.png">

- there is no wasted space. You don't need to hide CI columns or remove the duplicate half
- It's easy to sort by animal name or value
- I can also make the value columns background with gray gradient to better separate them.

I updated the app and included both versions of summary table so you can play with it and compare them.

**Comment by xhdong-umd** [comment] 2018-02-01 16:23
@jmcalabrese @chfleming If we simplify the model name to just animal name when there is no conflict, should we also change the variogram/home range plot title from the `animal - model type` full name to just animal name?

**Comment by xhdong-umd** [comment] 2018-02-01 16:34
I found I better change them too. Because both the overlap result matrix names and the plot titles come from the names of the home range list, they need to be consistent.

**Comment by xhdong-umd** [comment] 2018-02-01 16:52
I also need to change the map part, because there are layers of animal locations and home ranges. Previously the location layer name is animal name, home range layer name is `id - model type` full name, now there will be conflicts. 

I'm thinking changing the home range layer name to `id - range` format when there is no duplicates.

**Comment by xhdong-umd** [comment] 2018-02-01 17:23
I took option 1 as it is easier to read in simple cases.

<img width="688" alt="screen shot 2018-02-01 at 12 22 34 pm" src="https://user-images.githubusercontent.com/25039897/35692947-acf01530-074a-11e8-9c00-44088bb85915.png">

**Comment by xhdong-umd** [comment] 2018-02-01 17:25
Sorting table and plot at the same time is also done.

When you input a word to filter the table, the plot also updates.

**Comment by xhdong-umd** [comment] 2018-02-01 19:16
Previously I added a location plot tab in overlap page. Now I think maybe it's better to just use the map tab for this purpose.

<img width="714" alt="screen shot 2018-02-01 at 2 15 44 pm" src="https://user-images.githubusercontent.com/25039897/35698229-6f935688-075a-11e8-9149-0cd73feb1b69.png">


The only benefit from a separate location plot tab is that we can also make the location plot respond to selected overlaps thus highlight them. Though the map page also have layer selectors to check a subset only.

Should we just remove this tab?

**Comment by chfleming** [comment] 2018-02-01 19:19
I think what most of us want on the location tab is that after selecting one row from the table, the location tab will show a plot of the two animal's locations and home ranges.

If multiple rows are selected, I suppose you could show a grid of plots.

**Comment by xhdong-umd** [comment] 2018-02-01 19:26
Previously I planned to add some interactivity between the table and the value range plot:
- click on table to highlight part of plot
- click plot to highlight table

Now with the sorting and filtering working, I think this is not really needed anymore. It's very easy to map from table to plot.
<img width="692" alt="screen shot 2018-02-01 at 2 23 11 pm" src="https://user-images.githubusercontent.com/25039897/35698649-af125772-075b-11e8-814f-b9b8f9f68c57.png">
<img width="688" alt="screen shot 2018-02-01 at 2 23 18 pm" src="https://user-images.githubusercontent.com/25039897/35698656-b7cb876c-075b-11e8-8286-356dd81d48b5.png">


Sorted
<img width="696" alt="screen shot 2018-02-01 at 2 23 56 pm" src="https://user-images.githubusercontent.com/25039897/35698668-c55ad496-075b-11e8-9f22-590fbe994e0d.png">
<img width="695" alt="screen shot 2018-02-01 at 2 24 07 pm" src="https://user-images.githubusercontent.com/25039897/35698673-c837cf52-075b-11e8-822a-ae0fbdc235aa.png">



Filtering

<img width="718" alt="screen shot 2018-02-01 at 2 24 21 pm" src="https://user-images.githubusercontent.com/25039897/35698703-db584d46-075b-11e8-8f17-563e50db4826.png">
<img width="682" alt="screen shot 2018-02-01 at 2 24 33 pm" src="https://user-images.githubusercontent.com/25039897/35698709-df850ca6-075b-11e8-983e-7cdb14b4a3f0.png">

**Comment by xhdong-umd** [comment] 2018-02-01 19:55
I agree a group of plots of overlap pairs will be most helpful. Though we will need 15 plots for 6 animals, (n**2 - n)/2 for more animals. 

Is this acceptable?

**Comment by chfleming** [comment] 2018-02-01 19:56
I would only plot the selected pairs.

**Comment by xhdong-umd** [comment] 2018-02-01 19:59
And my previous plan of two direction interactivity can cause a loop:

- selecting rows in table highlight plot parts
- selection plot parts will select rows in table, which could cause update again because row selection in table itself trigger changes in plot.

It should still doable, maybe with some additional refreshes.

It'll be much simpler if we only do one direction:
- selecting rows in table highlight plot parts
- the location plot also update for selected rows.

Is this enough?

**Comment by xhdong-umd** [comment] 2018-02-01 20:01
For the variogram plot of models, should we use animal name only or the `animal - model type` as plot title?

**Comment by chfleming** [comment] 2018-02-01 20:02
I don't think you would want to have one big plot, but zoomed in plots of the pairs. In many cases, individuals will be very spread out.

**Comment by chfleming** [comment] 2018-02-01 20:04
I would only include the model name in cases where models are being compared.

**Comment by xhdong-umd** [comment] 2018-02-01 20:04
I agree. So we will keep the location plot tab

- draw overview plot by default (we need to have something in the beginning when nothing is selected)
- with rows in table selected, switch to group plot of pairs

**Comment by xhdong-umd** [comment] 2018-02-01 20:06
I'm referring to this plot:

<img width="706" alt="screen shot 2018-02-01 at 3 05 22 pm" src="https://user-images.githubusercontent.com/25039897/35700584-5fb1351c-0761-11e8-91ab-eb9bfb3649de.png">

It can be changed to similar arrangement of home range plot, i.e.
- use animal name only when there is no multiple models from same animal
- use `animal name - model type` name when there is multiple models.

But I feel the current arrangement is somewhat useful to always show the model detail in this place.

**Comment by chfleming** [comment] 2018-02-01 20:07
I think that's probably fine as is.

**Comment by xhdong-umd** [comment] 2018-02-01 20:09
OK. I will work on the paired location plots.

Is one direction interactivity from table to plot enough? i.e. no "clicking on plot to highlight rows in table".

**Comment by chfleming** [comment] 2018-02-01 20:11
I don't have a preference for the reverse direction. @jmcalabrese @NoonanM

**Comment by xhdong-umd** [comment] 2018-02-01 21:45
Selecting table rows will change color of corresponding values in plot.

<img width="942" alt="screen shot 2018-02-01 at 4 42 40 pm" src="https://user-images.githubusercontent.com/25039897/35704953-0aae1702-076f-11e8-852b-c1d149671e1a.png">

It's difficult to have more specific non-default color mappings in ggplot. For example I wanted to just keep non-selected values in blue point and red error bar, and change selected ones to other color. That means two separate color palette for point and error bar, which is quite difficult. Hopefully the current state is good enough.

**Comment by xhdong-umd** [comment] 2018-02-02 13:58
For the overlap summary table, do you want to sort by `ML` value descendingly by default?

**Comment by chfleming** [comment] 2018-02-02 18:18
That makes sense to me.

**Comment by xhdong-umd** [comment] 2018-02-02 19:05
I have finished the grouped location plot of overlap pairs, made the summary table sorted by default.

There is a brief error message in certain cases #48, I have to leave it as is now since I have spent several hours on it without success.

Previously we talked about "jump to home range page if user clicked overlap page directly". That turned out to be difficult because it's hard to determine whether the home range is available. It could be updating and not NULL. The only way to do that seemed to be maintain a page click history and check the history, then there could be multiple corner cases of different click combinations.

I think most user will not jump to overlap directly like what I did, so I'm leaving this as is now too.

Other than this two points, all discussed features above have been implemented. I have updated the app and you can try it out.

**Comment by xhdong-umd** [comment] 2018-02-03 01:33
I managed to silent the warning and error messages for the special case. That should be enough because it only happened briefly then update to correct data automatically.

**Comment by xhdong-umd** [comment] 2018-02-05 17:57
I have finished the help page for overlap, and is looking at the parallel functions for integration into ctmm now.

**Comment by xhdong-umd** [comment] 2018-02-15 15:24
I'm experimenting with home range plots.

Here is location points and home range contours

`plot(tele_list_sub3, UD = hrange_list_sub3, col = c("red", "blue"),
     labels = names(tele_list_sub3))`

<img width="1135" alt="screen shot 2018-02-15 at 10 09 51 am" src="https://user-images.githubusercontent.com/25039897/36263554-7426a02c-1238-11e8-8d0b-ee6647bc3789.png">

Without location points

`plot(hrange_list_sub3, col.level = c("red", "blue"),
     labels = names(tele_list_sub3))`

<img width="1139" alt="screen shot 2018-02-15 at 10 10 03 am" src="https://user-images.githubusercontent.com/25039897/36263633-992f835c-1238-11e8-8df5-d3c94e9deaca.png">

I'm not familiar with base plot, and I'm not sure how to customize these issues:

1. The home range contour label is a little bit small and not obvious. A bigger font or bold  should be better.

Here is another plot (there are 3 animals in plot while we only need plot of pairs, but I want to use this plot to show that when two animals are far away and stretched plot to bigger scale, it's even more difficult to read the labels.

<img width="1138" alt="screen shot 2018-02-15 at 10 13 38 am" src="https://user-images.githubusercontent.com/25039897/36263838-1c5e84a8-1239-11e8-9670-adc514339fb8.png">


2. Maybe we should only draw one contour for each home range by default? Of course we can add an input to customize levels, just like the other pages.

3. Should we remove the grid and density function to make the overlapped pair easy to read?

**Comment by NoonanM** [comment] 2018-02-15 16:45
I would remove the grid for sure. I don't think it adds any additional information at this stage. I think it would also be good to change the color of the UDs for each individual.

I would also consider removing the labels on the confidence interval contours.

**Comment by xhdong-umd** [comment] 2018-02-15 16:52
By color of the UDs do you mean the blue density in plot? I'm not sure if mixed colors in overlapped area will work well.

<img width="1108" alt="screen shot 2018-02-15 at 11 52 27 am" src="https://user-images.githubusercontent.com/25039897/36269249-b83f61a0-1246-11e8-941c-1c0b89c4ad75.png">


If we removed the labels on contours, we will need a color legend or some other label to show which  is which.

**Comment by NoonanM** [comment] 2018-02-15 16:58
Yes that's what I meant. I personally find the different colours more informative. The information on the overlap estimate comes from the density estimate, so it's good to see where the high/low density regions for each animal are.

**Comment by xhdong-umd** [comment] 2018-02-15 17:02
OK, actually we can make them all as options. By default all will be shown, user can toggle off some elements if they are too busy for a specific plot.
- location points - maybe turn this off by default?
- density
- contours

**Comment by NoonanM** [comment] 2018-02-15 17:05
Yes, that makes sense. I think locations and labels off by default is the cleanest baseline option?

**Comment by xhdong-umd** [comment] 2018-02-15 17:07
If we decide to use a color legend in case label is off, then maybe we can disable label all together, since the current label font is too small/fade anyway.

**Comment by NoonanM** [comment] 2018-02-15 17:08
I think the legend option is a better idea.

**Comment by xhdong-umd** [comment] 2018-02-15 18:18
I think we can use home range plot as default and put the current ggplot2 points plot into another tab. It could be a useful option.

**Comment by xhdong-umd** [comment] 2018-02-22 18:40
The legend for base plot is placed inside the plot region by default. If I draw both location points and home range contours, then add legend for them, the legend could take too much space and overlap with plot.

It's possible to move the legend outside but the parameter often need manual tweaking depend on legend name lengths.

I'm inclined to just disable location points in this plot, which make the home range contour and density easier to read, and we have the ggplot point plot tab if user need to check the location points.

**Comment by xhdong-umd** [comment] 2018-02-22 21:02
So I'm planning to just draw contour and densities, with a color legend.

<img width="323" alt="screen shot 2018-02-22 at 4 00 58 pm" src="https://user-images.githubusercontent.com/25039897/36563924-98713a30-17e9-11e8-8eb0-d69f10b8ae96.png">

There is no need for controls of layers since we only have contours and densities, and they don't interfere with each other.

**Comment by xhdong-umd** [comment] 2018-02-22 21:04
How should I remove the grids? I only saw `col.grid`, which is not really an option to turn it off unless I make some transparent color?

**Comment by chfleming** [comment] 2018-02-23 02:15
I think `col.grid=NA` disables the grid.

**Comment by xhdong-umd** [comment] 2018-02-23 16:04
`col.grid=NA` worked, thanks!

<img width="317" alt="screen shot 2018-02-23 at 11 04 24 am" src="https://user-images.githubusercontent.com/25039897/36603614-5a826cd0-1889-11e8-8695-d4df6cc928ae.png">
<img width="316" alt="screen shot 2018-02-23 at 11 04 34 am" src="https://user-images.githubusercontent.com/25039897/36603618-5c1a0ec2-1889-11e8-91a4-5af30c0779b0.png">

**Comment by xhdong-umd** [comment] 2018-02-23 21:19
I found legend positioning in base plot is really cumbersome. 
- By default it was placed inside the plot box, and it can get lost if you resize the plot window size. 
- With some hack you can put legend outside of the plot, but that involves a lot of tweaking of `par`, also not reliable with more plots and resizing of plots.

I'm thinking maybe just put animal names in plot title, and color the overlap table cells instead.

**Comment by xhdong-umd** [comment] 2018-03-01 19:38
In home range plots we can give a vector of `level.UD` and several polygons can be plotted. When using plot with a list of home range UD, a vector of `level.UD` seemed to be distributed to each UD object, so we cannot have multiple level polygons.

Should we just put a single value input for this `level.UD`?

**Comment by chfleming** [comment] 2018-03-01 21:45
You mean different level.UD per individual? I'm not sure that anyone would want that.

**Comment by xhdong-umd** [comment] 2018-03-01 21:49
Oh I was thinking the confidence levels of contour in home range page, that was `level`.  

<img width="674" alt="screen shot 2017-08-18 at 10 11 10 am" src="https://user-images.githubusercontent.com/25039897/29462571-d1a4c9b4-83fd-11e7-8d6b-fc17f5a3cc59.png">

Do we need a `level` input here, or a `level.UD` input here?

**Comment by chfleming** [comment] 2018-03-01 22:13
My assumption is that people will mostly want to specify `level.UD`, with `0.95` and `0.50` being the most popular choices. However, some people will also want to disable `level` with `level=NA` to avoid clutter.

**Comment by xhdong-umd** [comment] 2018-03-05 19:53
It's easy to confuse between `level` and `level.UD` for me. Howe should we describe them in the app? We will need to show both of them here.

- `level.UD`: Confidence level of contour. (single value by definition)
- `level`: Confidence levels placed on the contour themselves

**Comment by xhdong-umd** [comment] 2018-03-05 20:29
I added controls but not really satisfied with the descriptions.

<img width="715" alt="screen shot 2018-03-05 at 3 29 30 pm" src="https://user-images.githubusercontent.com/25039897/36998170-0608e824-208a-11e8-9d51-57e1681211a4.png">

**Comment by chfleming** [comment] 2018-03-05 20:32
How about something like "% coverage of the individuals" for `level.UD` and "% coverage of the uncertainty" for `level`.

**Comment by xhdong-umd** [comment] 2018-03-05 20:46
That's much better. I'll also add notes in help document, though many users probably will not look at it, so it's better to be more clear in app from the beginning.

**Comment by xhdong-umd** [comment] 2018-03-09 17:10
@chfleming , I'm trying to turn of the contours with `level.UD = NA`. However there will be error if both home range and contours are plotted.

```r
# this works
plot(hrange_list_sub2[[1]], level.UD = NA)
# with point there is error
plot(tele_list_sub2[1], UD = hrange_list_sub2[[1]], level.UD = NA)
# Error in if (level.UD == 1 || (!is.na(level) && level == 1 && !is.null(x$DOF.area))) { : 
#  missing value where TRUE/FALSE needed
```

**Comment by xhdong-umd** [comment] 2018-03-09 19:58
@NoonanM I tried to call `title` twice to use two colors in plot title. The second call need to adjust the position, but we don't know beforehand how much space will be needed. So it's easy to create one time use script with some tweaking, but difficult to place two names (they could be quite long) reliably.

I found [some hack using expression](https://stackoverflow.com/questions/17083362/colorize-parts-of-the-title-in-a-plot), but that format cannot be used directly because I need to use variable here, which will not be evaluated inside `expression`. Maybe it's possible to do that with some advanced non-standard evaluation tricks, but the whole approach goes too far in hacking.

```r
title(expression("title (" * phantom("slope=1)") * ")"), col.main = "black")
title(expression(phantom("title (") * "slope=1"), col.main = "red")
```

**Comment by chfleming** [comment] 2018-03-09 20:14
This function looks like it would work using a black comma as the middle input:

http://r.789695.n4.nabble.com/title-words-in-different-colors-td878698.html#a878700

**Comment by xhdong-umd** [comment] 2018-03-09 20:18
OK, so they just calculate the name width and place them...

Hope it will not break by some special characters in animal names.

**Comment by chfleming** [comment] 2018-03-09 20:22
It looks like they use the `phantom` trick, which should work unless there are bugs in `phantom`.

**Comment by xhdong-umd** [comment] 2018-03-09 20:25
Is it possible to draw location points but with contours off for home range? If that's not possible, I can simple make a radiobutton to switch between `location points` and `hide contours`.

**Comment by chfleming** [comment] 2018-03-09 20:53
I'll fix this momentarily.

**Comment by chfleming** [comment] 2018-03-09 23:33
Regarding `level.UD=NA`, there were 2 issues:

1) `plot.UD` was not passing `level` or `level.UD` arguments to the plot extent calculation. It should have crashed for you as well. I have fixed this in the master branch just now.
2) `level.UD` is necessary to calculate the plotting extent of the UD, even if the contours are not wanted.

Regardless, `col.level=NA` turns off the contour plotting.

**Comment by xhdong-umd** [comment] 2018-03-10 01:03
OK. So I'll just use `col.level = NA`, and don't allow NA of `level.UD`.

**Comment by xhdong-umd** [comment] 2018-03-10 01:50
We have a checkbox `confidence envelops` in overlap home range plot to turn off `level`. Do we need this option in home range and occurence page too?

**Comment by chfleming** [comment] 2018-03-10 01:52
Its less important there because there is less clutter and the CIs are one of the more important features of the software, but it wouldn't hurt anything to have it.

**Comment by xhdong-umd** [comment] 2018-03-10 01:55
So add the checkbox but make the default to be on? The overlap home range page have default to off.

**Comment by chfleming** [comment] 2018-03-10 19:52
> So add the checkbox but make the default to be on?

Yes, the default should definitely be CIs on in the home-range page.

> The overlap home range page have default to off.

That's probably okay.

> Also should we add a checkbox in home range to turn location points on/off?

It wouldn't hurt anything and the default should be on.

**Comment by xhdong-umd** [comment] 2018-03-10 22:26
For occurence plot, the interval `level` doesn't have effect? 

And the location point in occurrence plot doesn't provide more information, right?

**Comment by chfleming** [comment] 2018-03-10 22:35
We don't put uncertainty on the occurrence distribution contours because the occurrence distribution itself is uncertainty in where the animal was.

Locations on the occurrence plot should be optional.

**Comment by xhdong-umd** [comment] 2018-03-11 00:45
OK. These are some screenshot with each one's default values.

<img width="703" alt="screen shot 2018-03-10 at 7 43 04 pm" src="https://user-images.githubusercontent.com/25039897/37248269-7bf7f8e4-249b-11e8-905d-e9955314217f.png">

<img width="692" alt="screen shot 2018-03-10 at 7 43 21 pm" src="https://user-images.githubusercontent.com/25039897/37248270-7e3f3c66-249b-11e8-8b30-6f2b5ca95db3.png">

<img width="697" alt="screen shot 2018-03-10 at 7 44 51 pm" src="https://user-images.githubusercontent.com/25039897/37248271-8816fe86-249b-11e8-931c-657c4592c68c.png">

**Comment by xhdong-umd** [comment] 2018-03-11 19:27
I made the multi color title to be separate lines, otherwise the margin is probably not enough for long names

<img width="699" alt="screen shot 2018-03-11 at 3 26 01 pm" src="https://user-images.githubusercontent.com/25039897/37257487-9129823c-2540-11e8-92ff-f3342468a535.png">

<img width="700" alt="screen shot 2018-03-11 at 3 25 36 pm" src="https://user-images.githubusercontent.com/25039897/37257488-983b6630-2540-11e8-9718-797d766cda99.png">

**Comment by vestlink** [comment] 2018-03-16 07:53
Will the Occurence distirubution overlap be considered at some point?

**Comment by chfleming** [comment] 2018-03-16 19:04
Hi @vestlink , I don't know what legitimate use an occurrence distribution overlap would have. Integrating the occurrence distribution over an area gives the point estimate for the fraction of time spent in that area. Similarity in occurrence would come down to similarities in times spent, which I do not think would relate to statistical/distribution overlap, but something else.

More likely people would use occurrence distribution overlap to compare space use, which would be an incorrect interpretation.

**Comment by NoonanM** [comment] 2018-03-29 18:41
A user just ran into an issue with the visuals on the overlap tab. See attached screenshot.
![screenshot error](https://user-images.githubusercontent.com/26824892/38107214-44f49230-335f-11e8-8847-4a184cbd7514.png)

**Comment by xhdong-umd** [comment] 2018-03-29 18:45
That seemed to be the group plot of home ranges. So there are 630 pairs? By default the home range plot only draw pairs with positive overlap, but that could be still too much. It's impossible to show hundreds of plot in same page.

I think I need to add some limit, like the visualization page, only draw plot for current page.

**Comment by NoonanM** [comment] 2018-03-30 13:31
The overlap pairs generally look very good, but I've noticed that sometimes you can get pairs of animals with very similar colours, making some plots hard to interpret. Would it be possible to include an option to e.g., make the contours black, or greyscale the colours of certain plots?

**Comment by xhdong-umd** [comment] 2018-03-30 13:42
When we plotting multiple pairs, the colors are chosen automatically on a color space using max distance possible. With a lot of pairs, it's unavoidable that some colors will become similar (the color started in another round, so color `c` might be different from `d` but close to `a`).

Right now the density color and contours color are same for one animal, and we use that color for animal name in plot as legend.

If you want to just change the contours color and keep the density color, we will need to describe two colors in legend. That's still doable, like `[Cilla]`, use contour color for `[]`, density color for `Cilla`. This is not perfect since density color will be similar, but at least we have some boundaries. This may not look as good as current color for smaller numbers of animal though.

If you want to change individual plot color, that'll break all color mapping and create too many problems.

Another approach to temporarily reduce the problem is to select a smaller subset in visualization page, so that the colors will not be used up.

**Comment by chfleming** [comment] 2018-03-30 16:09
> When we plotting multiple pairs, the colors are chosen automatically on a color space using max distance possible. With a lot of pairs, it's unavoidable that some colors will become similar (the color started in another round, so color c might be different from d but close to a).

On that topic, getting the color wheel to cycle through the animals while optimizing some objective on neighboring color separation versus distance is more complicated than I expected. You have to first define an objective function that penalizes vertices that are close in both color and distance. Then you have to be able to minimize that objective function via color assignment with reasonable computational cost. Its not a high priority, fortunately.

**Comment by NoonanM** [comment] 2018-03-30 16:48
Ok, I had hoped it might be easy to be able to adjust the contours of individual plots on the overlap page (like a black/white tick box that only applies to the overlap page), but if that's not the case then I think you can just leave everything like it is.

**Comment by xhdong-umd** [comment] 2018-03-30 19:10
We can make a simple change for the similar color case, just have an option to use fixed colors (blue/red) for every plot. This is simple enough and will not be too hard to implement. It does have several disadvantages:
- it will be inconsistent with other pages, like visualization and home range, maps
- it will inconsistent across animals, same animal can be different color in different plot
- it doesn't look as good as before

We can make it to be a non-default option so only enable it when needed. @NoonanM Will this solve the problem you found?

**Comment by xhdong-umd** [comment] 2018-03-30 19:13
And for the error above, I checked and found the app is already only plotting the pairs in the current page. 

It seemed that the app in case is showing 72 rows in one page, and that means the app need to draw 72 plot together. That will be unnecessary, since each plot will be too small to see anything. I don't think there is a solution for this, you have to choose a smaller count for page.

**Comment by NoonanM** [comment] 2018-03-30 19:20
Ok, in terms of the error, maybe it might be worth mentioning in the help file that the fix is to use a smaller count? That way users at least have a path forward.

As for the color issue, it's not a major problem, but can make certain figures difficult to interpret. I think the non-default option you mentioned would be a pretty good way of taking care of that.

**Comment by xhdong-umd** [comment] 2018-03-30 19:46
I added notes in help, also just removed the page length option of 72, which is too much for this page.

**Comment by xhdong-umd** [comment] 2018-03-30 20:29
This is the two colors mode

<img width="698" alt="screen shot 2018-03-30 at 4 29 32 pm" src="https://user-images.githubusercontent.com/25039897/38152843-92e3b434-3437-11e8-896e-50a3ec1cc0f0.png">

**Comment by NoonanM** [comment] 2018-03-30 21:52
That looks great. I think it will definitely be useful for those cases where colours are too similar to distinguish clearly.

**Comment by NoonanM** [comment] 2019-05-23 14:25
On the overlap page, it is not currently possible to subset individuals. It would be useful to have the option to select what individuals overlap is calculated for.

**Comment by xhdong-umd** [comment] 2019-05-23 14:44
I think overlap of all combinations of selected individuals have been calculated. To change selected individuals, user need to go back to visualization page, since this the assumption throughout the app, and all modeling calculations are based on same individual selection - - if you change selection in overlap page, you still need to get model results for these individuals first, before getting the overlap.

**Comment by NoonanM** [comment] 2019-05-23 15:07
But if a user has done model fitting on all individuals, and then wants to only look at overlap on a subset, they would need to re-run all of their analyses. The main use here is so that users can have plots of overlap values that reflect the individuals they are interested in.

**Comment by xhdong-umd** [comment] 2019-05-23 15:14
I will need to look at the details of the page. It could be possible to limit to a subset within page, but not changing to a different individual set with model results unavailable.

**Comment by NoonanM** [comment] 2019-05-23 15:22
Yes, the use case would be only for individuals that have model results. Maybe some type of drop down menu, or clickable list of individuals with all selected by default?

**Comment by xhdong-umd** [comment] 2019-10-19 14:16
I'm closing this issue as it's quite long, and move the newest request as an independent issue #103

**Closed by xhdong-umd** 2019-10-19 14:16 UTC
Labels: Done, Future
